name: ⚡ Get X.com Graphs Posts

on:
  repository_dispatch:
    types: [get-x-graph-posts]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: twitter-account-2
  cancel-in-progress: false

jobs:
  get_graph_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
        name: Install deps

      - run: npx playwright install --with-deps firefox
        name: Install Playwright browsers

      - name: Run bot
        env:
          DISCORD_TOKEN:   ${{ vars.DISCORD_TOKEN }}
          DISCORD_TWITTER_GRAPHS_WEBHOOK: ${{ vars.DISCORD_TWITTER_GRAPHS_WEBHOOK }}
          X_USERNAMES:     ${{ vars.X_GRAPH_USERNAMES }}
          X_COOKIE_HEADER: ${{ vars.X_COOKIE_HEADER }}
        run: node twitter_graphs/index.mjs

      - name: Commit state
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull --rebase --autostash origin main
          
          # enable nullglob so non-matching globs are removed
          shopt -s nullglob

          # Stage only existing files
          files=(twitter_graphs/last_link_*.json)
          for file in "${files[@]}"; do
            if [[ -f "$file" ]]; then
              git add "$file"
            fi
          done

          # Check for debug files in twitter directory (adjust path if needed)
          for file in x.com/debug_*.html; do
            if [[ -f "$file" ]]; then
              git add "$file"
            fi
          done

          git diff --cached --quiet || git commit -m "Update last seen links"
          git push
